name: default_app
description: Kideliver Web App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  get: ^3.22.2

  parse_server_sdk_flutter: ^2.0.1

  dio: ^3.0.10
  # path_provider: ^1.6.14
  # intro_slider: ^2.2.9
  modal_progress_hud: ^0.1.3
  keyboard_dismisser: ^1.0.2
  adaptive_dialog: ^0.9.3
  cached_network_image: ^2.3.3
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.0
  font_awesome_flutter: ^8.10.0
  # file_picker: ^2.1.0
  pluto_grid: ^0.1.21
  charts_flutter: ^0.9.0
  latlong: ^0.6.1
  timeline_tile: ^1.0.0
  auto_size_text: ^2.1.0
  google_fonts: ^1.1.1
  maps_launcher: ^1.2.2+2
  flutter_summernote: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/